baseURL = "http://jackwang.cn/"
languageCode = "zh-CN"
title = "Cool Web - Jack Wang"
theme = "webstack-hugo"
preserveTaxonomyNames = true
disablePathToLower = true
hasCJKLanguage = true
copyright = "Jack Wang"
[params]
  author = "Jack Wang"
  description = "Webstack Hugo"
[params.search]
  enable = false
[params.darkmode]
  enable = false
[caches]
  [caches.getjson]
    dir = ':cacheDir/:project'
    maxAge = '1h'
